# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'worklifeinjapan' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for worklifeinjapan
  pod 'Firebase/Messaging'

  target 'worklifeinjapan-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'worklifeinjapanTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'worklifeinjapan-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for worklifeinjapan-tvOS

  # target 'worklifeinjapan-tvOSTests' do
    # inherit! :search_paths
    # Pods for testing
  # end

# end
